### ISSUE TITLE
 Found word count error

### ISSUE THREAD

**Issue by Mofisto** [theme-next/hexo-symbols-count-time#30]
This is  [blog](https://wuhash.com)，I use Chinese and English，The number of words counted is wrong

**Comment by LeoJhonSong** [comment]
duplicate of #17

**Comment by xmasong** [comment]
I'm face the same issue，I guess this is related to markdown. See a example: 
I only input 'a', wordcount === 9：
![image](https://user-images.githubusercontent.com/22997127/60707597-b2ea5080-9f3e-11e9-840f-c09d59220138.png)
But when I input '# a', wordcount === 63:
![image](https://user-images.githubusercontent.com/22997127/60707662-d44b3c80-9f3e-11e9-8d3a-a349bc9d53ca.png)

**Comment by xmasong** [comment]
![image](https://user-images.githubusercontent.com/22997127/60752608-2b621780-9ffa-11e9-958b-e521869e73e4.png)
Added console, you can see that although post.length is updated by filter, the old time is displayed in html.

**Comment by xmasong** [comment]
oh, I solved by updating theme/next to 7.2.0

**Comment by HillBamboo** [comment]
> oh, I solved by updating theme/next to 7.2.0

I meet the issue that, "本文字数" is displayed as "Symbols count in article" and "阅读时长" is displayed as 
"Reading time". The issue is illustrated as the following picture:
![image](https://user-images.githubusercontent.com/10396980/61506142-c18f3800-aa13-11e9-82b4-cec343aa29b4.png)

I already set "language : zh-Hans" in hexo's _config.yml file, but it didn't work. 
My theme/next version is 7.1.2. And my configuration partially in that file is:

```yaml
 symbols_count_time:
   symbols: true
   time: true
   total_symbols: true
   total_time: true
   exclude_codeblock: false
```

How can I solve it?
Thanks.

**Comment by 1v9** [comment]
@HillBamboo `language : zh-CN`

**Comment by HillBamboo** [comment]
@1v9 thank you so much 👍 👍 👍
